/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author davidcaamal
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        showPanel(new PCaptura());
    }
    
    public void EntradaFrame(String idUserName, String idUserImg){
        lblUserName.setText(idUserName);
        lblImageUser.setText(idUserImg);
    }

    private void showPanel(JPanel pageActual){
        pageActual.setSize(425, 400);
        pageActual.setLocation(0,0);
        
        jpanelContainer.removeAll();
        jpanelContainer.add(pageActual, BorderLayout.CENTER);
        jpanelContainer.revalidate();
        jpanelContainer.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImageUser = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        btnCerrarSession = new javax.swing.JButton();
        jpanelContainer = new javax.swing.JPanel();
        jMenuPrincipal1 = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        Captura = new javax.swing.JMenuItem();
        Detalle = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImageUser.setText("jLabel1");

        lblUserName.setText("jLabel2");

        btnCerrarSession.setText("Cerrar Sesión");

        jpanelContainer.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpanelContainerLayout = new javax.swing.GroupLayout(jpanelContainer);
        jpanelContainer.setLayout(jpanelContainerLayout);
        jpanelContainerLayout.setHorizontalGroup(
            jpanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        jpanelContainerLayout.setVerticalGroup(
            jpanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jMenuPrincipal.setText("Administración");

        Captura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Captura.setText("Captura");
        Captura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CapturaMouseClicked(evt);
            }
        });
        Captura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapturaActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(Captura);

        Detalle.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Detalle.setText("Detalle");
        Detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetalleMouseClicked(evt);
            }
        });
        Detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetalleActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(Detalle);

        jMenuPrincipal1.add(jMenuPrincipal);

        jMenu2.setText("Acerca de ...");
        jMenuPrincipal1.add(jMenu2);

        jMenu3.setText("jMenu3");
        jMenuPrincipal1.add(jMenu3);

        setJMenuBar(jMenuPrincipal1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jpanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSession)
                    .addComponent(lblUserName)
                    .addComponent(lblImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblImageUser, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUserName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarSession)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jpanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CapturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CapturaMouseClicked
        // TODO add your handling code here:
        //showPanel(new PCaptura());
    }//GEN-LAST:event_CapturaMouseClicked

    private void DetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetalleMouseClicked
        //showPanel(new PDetalle());
    }//GEN-LAST:event_DetalleMouseClicked

    private void CapturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapturaActionPerformed
        // TODO add your handling code here:
        showPanel(new PCaptura());
    }//GEN-LAST:event_CapturaActionPerformed

    private void DetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetalleActionPerformed
        // TODO add your handling code here:
        showPanel(new PDetalle());
    }//GEN-LAST:event_DetalleActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    */
        //</editor-fold>

        /* Create and display the form */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Captura;
    private javax.swing.JMenuItem Detalle;
    private javax.swing.JButton btnCerrarSession;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JMenuBar jMenuPrincipal1;
    private javax.swing.JPanel jpanelContainer;
    private javax.swing.JLabel lblImageUser;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables
}
